# states.py

def get_states_ids():
    return {
        "Alabama": 1,
        "Alaska": 4,
        "American Samoa": 7,
        "Arizona": 10,
        "Arkansas": 13,
        "Armed Forces Africa": 16,
        "Armed Forces Americas": 19,
        "Armed Forces Canada": 22,
        "Armed Forces Europe": 25,
        "Armed Forces Middle East": 28,
        "Armed Forces Pacific": 31,
        "California": 34,
        "Colorado": 37,
        "Connecticut": 40,
        "Delaware": 43,
        "District of Columbia": 46,
        "Federated States Of Micronesia": 49,
        "Florida": 52,
        "Georgia": 55,
        "Guam": 58,
        "Hawaii": 61,
        "Idaho": 64,
        "Illinois": 67,
        "Indiana": 70,
        "Iowa": 73,
        "Kansas": 76,
        "Kentucky": 79,
        "Louisiana": 82,
        "Maine": 85,
        "Marshall Islands": 88,
        "Maryland": 91,
        "Massachusetts": 94,
        "Michigan": 97,
        "Minnesota": 100,
        "Mississippi": 103,
        "Missouri": 106,
        "Montana": 109,
        "Nebraska": 112,
        "Nevada": 115,
        "New Hampshire": 118,
        "New Jersey": 121,
        "New Mexico": 124,
        "New York": 127,
        "North Carolina": 130,
        "North Dakota": 133,
        "Northern Mariana Islands": 136,
        "Ohio": 139,
        "Oklahoma": 142,
        "Oregon": 145,
        "Palau": 148,
        "Pennsylvania": 151,
        "Puerto Rico": 154,
        "Rhode Island": 157,
        "South Carolina": 160,
        "South Dakota": 163,
        "Tennessee": 166,
        "Texas": 169,
        "Utah": 172,
        "Vermont": 175,
        "Virgin Islands": 178,
        "Virginia": 181,
        "Washington": 184,
        "West Virginia": 187,
        "Wisconsin": 190,
        "Wyoming": 193
    }
